name: easy_web_view
description: A super simple webview for Flutter Web, Mobile and Desktop
version: 1.6.2
homepage: https://github.com/rodydavis/easy_web_view
repository: https://github.com/rodydavis/plugins
maintainer: Rody Davis (@rodydavis)
environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.14
  flutter_widget_from_html_core: ^0.14.12
  html2md: ^1.2.6
  http: ^1.1.0
  markdown: ^7.0.2
  permission_handler: ^10.2.0
  url_launcher: ^6.1.10
  webview_flutter: ^4.1.0
  webview_windows: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
