name: easy_web_view
description: A super simple webview for Flutter Web, Mobile and Desktop
version: 3.1.0
homepage: https://github.com/rodydavis/easy_web_view
repository: https://github.com/rodydavis/easy_web_view
maintainer: Rody Davis (@rodydavis)
environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  permission_handler: ^12.0.1
  webview_flutter: ^4.13.0
  webview_windows: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
